services:
  app:
    build: .
    depends_on:
      - database
      - redis
    volumes:
      - .:/app
      - storage_data:/var/www/app_storage
      - gems_volume:/gems:cached
    env_file:
      - .env
    #ports:
    #  - 3000:3000
    tty: true

  redis:
    image: redis
    #ports:
    #  - 6378:6379
    volumes:
      - redis_data:/data

  database:
    image: postgres:16.1
    env_file:
      - .env
    #ports:
    #  - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    

  pgadmin:
    image: dpage/pgadmin4:latest
    env_file:
      - .env
    depends_on:
      - database
    #ports:
    #  - 7000:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin


volumes:
  db_data:
  redis_data:
  storage_data:
  gems_volume:
  pgadmin-data:
