apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: imageName-public-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: imageName-storage-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: imageName
spec:
  replicas: 1
  selector:
    matchLabels:
      ip-service: imageName
  template:
    metadata:
      labels:
        ip-service: imageName
    spec:
      containers:
        - name: imageName
          image: nuntius.azurecr.io/imageName:latest
          envFrom:
            - secretRef:
                name: secrets
            - configMapRef:
                name: host-map
          volumeMounts:
            - mountPath: /app/storage
              name: imageNamestoragedata
            - mountPath: /public
              name: imageNamepublicdata

      volumes:
        - name: imageNamestoragedata
          persistentVolumeClaim:
            claimName: imageName-storage-data
        - name: imageNamepublicdata
          persistentVolumeClaim:
            claimName: imageName-public-data

      imagePullSecrets:
        - name: nuntiusregistry
---
apiVersion: v1
kind: Service
metadata:
  name: imageName-service
spec:
  type: ClusterIP
  selector:
    ip-service: imageName
  ports:
    - port: 8080
      targetPort: 3000
