development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: <%= "redis://#{ENV.fetch('REDIS_HOST', 'redis')}:6379/#{Integer(ENV.fetch("REDIS_DB", 0))}" %>
  channel_prefix: puntos_production
