require "active_support/core_ext/integer/time"
require Rails.root.join('app/services/mailer_settings_service')


Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.
  config.hosts << "puntos.nuntius.tech"
  config.hosts << "puntosaltoque.com"
  config.hosts << "app.puntosaltoque.com"
  config.hosts.clear

  Rack::MiniProfiler.config.authorization_mode = :allow_authorized

  # In the development environment your application's code is reloaded any time
  # it changes. This slows down response time but is perfect for development
  # since you don't have to restart the web server when you make code changes.
  config.enable_reloading = true

  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # Enable/disable caching. By default caching is disabled.
  # Run rails dev:cache to toggle caching.
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.action_controller.perform_caching = true
    config.action_controller.enable_fragment_cache_logging = true

    config.cache_store = :memory_store
    config.public_file_server.headers = { "Cache-Control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false
    config.cache_store = :null_store
  end

  # Store uploaded files on the local file system (see config/storage.yml for options).
  config.active_storage.service = :local

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise exceptions for disallowed deprecations.
  config.active_support.disallowed_deprecation = :raise

  # Tell Active Support which deprecation messages to disallow.
  config.active_support.disallowed_deprecation_warnings = []

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = false

  # Highlight code that enqueued background job in logs.
  config.active_job.verbose_enqueue_logs = true

  # Debug mode disables concatenation and preprocessing of assets.
  # This option may cause significant delays in view rendering with a large
  # number of complex assets. Se agregó
  config.assets.debug = true

  # Suppress logger output for asset requests.
  config.assets.quiet = true

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  # config.action_view.annotate_rendered_view_with_filenames = true ----------------esto comente

  # Uncomment if you wish to allow Action Cable access from any origin.
  # config.action_cable.disable_request_forgery_protection = true

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = false

  # ------------------lo cambie a false o comente

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!

  # routes, locales, etc. This feature depends on the listen gem.
  # config.file_watcher = ActiveSupport::EventedFileUpdateChecker

  # Use an evented file watcher to asynchronously detect changes in source code,
  # routes, locales, etc. This feature depends on the listen gem. Se agregó
  config.file_watcher = ActiveSupport::EventedFileUpdateChecker

  # Uncomment if you wish to allow Action Cable access from any origin.
  # config.action_cable.disable_request_forgery_protection = true

    # Don't care if the mailer can't send.
  config.action_mailer.raise_delivery_errors = true

  # Disable caching for Action Mailer templates even if Action Controller
  # caching is enabled.
  config.action_mailer.perform_caching = false

  # Used for generating URLs inside email templates, ie: Email verification links: https://puntosaltoque.com/validate_email/token123
  # config.action_mailer.default_url_options = { host: "localhost", port: 3000 } ESTO ES PARA QUE ME ANDE LOCAL
  # config.action_mailer.default_url_options = { host: "infinite-jawfish-ready.ngrok-free.app" } ESTO ES PARA QUE ME ANDE NGROK
  # config.action_mailer.default_url_options = { host: "puntos.nuntius.tech" } # ESTO ES PARA QUE ME ANDE TESTING
  # config.action_mailer.default_url_options = { host: ENV["MAIL_DEFAULT_URL"] } #   ESTO ES PARA QUE ME ANDE CON ENVS
  # config.action_mailer.default_url_options = { host: "puntosaltoque.com" }
  # config.action_mailer.default_url_options = { host: "mail.puntosaltoque.com" }

  config.action_mailer.perform_deliveries = true

  config.action_mailer.logger = Rails.logger

  config.log_level = :debug

  # Configuracion para envio de mails

  # Desarrollo
  # config.action_mailer.delivery_method = :letter_opener_web

  # Produccion
  config.action_mailer.delivery_method = MailerSettingsService.delivery_method # smtp
  config.action_mailer.default_url_options = MailerSettingsService.default_url_options if MailerSettingsService.delivery_method==:smtp
  config.action_mailer.smtp_settings = MailerSettingsService.smtp_settings if MailerSettingsService.delivery_method==:smtp


  # config.action_mailer.smtp_settings = {
  #   address: "smtp.resend.com",
  #   port: 587,
  #   user_name: "resend",
  #   password: "re_ai6Rtvwp_6J1Yu344AmXW4bY7PePad6Km",
  #   authentication: :plain,
  #   enable_starttls_auto: true
  # }


  #   config.action_mailer.smtp_settings = {
  #   address: "smtp.envialosimple.email",
  #   port: 587,
  #   user_name: "MJyzWKw2G29cVnKk9af994ef@mail.puntosaltoque.com",
  #   password: "Nvm8EKHndfod7miAcj9cQFsgfogtB3ry",
  #   authentication: :plain,
  #   enable_starttls_auto: true
  # }

 # Configuracion vieja
  # config.action_mailer.delivery_method = :smtp
  # config.action_mailer.smtp_settings = {
  #   address:              "c2611577.ferozo.com",
  #   port:                 465,
  #   user_name:            "info@puntosaltoke.online",
  #   password:             "Tok3Punt@s24",
  #   authentication:       'login',
  #   enable_starttls_auto: true,
  #   ssl:                  true
  # }

  # config.action_mailer.delivery_method = :smtp
  # config.action_mailer.smtp_settings = {
  #   address:              "smtp.gmail.com",
  #   port:                 465,
  #   user_name:            "lgabregu@gmail.com",
  #   password:             "",
  #   authentication:       'login',
  #   enable_starttls_auto: true,
  #   ssl:                  true
  # }

end
